=== muntaswir72562/inventoryHub/inventoryhubphp/data/product.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:simpleType name="quantityType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1" />
        </xs:restriction>
    </xs:simpleType>  
    <xs:simpleType name="prodType">
      <xs:restriction base="xs:string">
          <xs:pattern value="p[0-9]{3}"/>
      </xs:restriction>
      </xs:simpleType>
<xs:element name="products">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="product" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string" />
              <xs:element name="description" type="xs:string" />
              <xs:element name="unitPrice" type="xs:decimal" />
              <xs:element name="quantity" type="quantityType" />
              <xs:element name="img">
                <xs:complexType>
                  <xs:attribute name="src" type="xs:string" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="prodType" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== muntaswir72562/inventoryHub/public/data/product.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="product1.xsl" type="text/xsl"?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="product.xsd">
    <product id="p001">
        <title>Shoes</title>
        <unitPrice>50</unitPrice>
        <quantity>5</quantity>
        <img src="shoe.jpeg"></img>
        <link>shoe.html</link>
        This is a shoe </product>
    <product id="p001">
        <title>Shoes</title>
      
        <unitPrice>50</unitPrice>
        <quantity>100</quantity>
        <img src="shoe.jpeg"></img>
        <link>shoe.html</link>
        This is a shoe </product>
    <product id="p001">
        <title>Shoes</title>
        <unitPrice>50</unitPrice>
        <quantity>100</quantity>
        <img src="shoe.jpeg"></img>
        <link>shoe.html</link>
        This is a shoe </product>
</products>

=== muntaswir72562/inventoryHub/inventoryphp/data/product.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="product.xsl" type="text/xsl"?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="product.xsd">
    <product id="p001">
        <title>Nike Shoes</title>
        <unitPrice>50</unitPrice>
        <quantity>5</quantity>
        <img src="shoe.jpg"></img>
        <link>shoe.html</link>
        Shoes are an essential part of our daily lives. They protect our feet from the harsh
        elements of the ground, provide support and comfort, and also serve as a fashion statement</product>
    <product id="p002">
        <title>Under Armour Shoes</title>
        <unitPrice>50</unitPrice>
        <quantity>100</quantity>
        <img src="shoe.jpg"></img>
        <link>shoe.html</link>
        Shoes come in a variety of styles, materials, and sizes, each designed to suit a particular
        purpose or occasion. From running shoes to formal dress shoes, from sandals to boots, there
        is a shoe for every need. </product>
    <product id="p001">
        <title>Jordan Shoes</title>
        <unitPrice>50</unitPrice>
        <quantity>100</quantity>
        <img src="shoe.jpg"></img>
        <link>shoe.html</link>
        Shoes have a rich history, dating back thousands of years when people used animal hides to
        protect their feet. Today, shoes are made using advanced technology and innovative
        materials, making them more durable and comfortable than ever before. </product>
</products>
