=== muntaswir72562/inventoryHub/public/data/purchaseOrder.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="orders">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="order">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="supplier">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="companyName" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="date" type="xs:string" />
              <xs:element name="status" type="xs:string" />
              <xs:element name="payment">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="type" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="item">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="name" type="xs:string" />
                    <xs:element name="quantity" type="xs:unsignedByte" />
                    <xs:element name="amount" type="xs:unsignedShort" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== muntaswir72562/inventoryHub/public/data/purchaseOrder.xml
<?xml version="1.0" encoding="utf-8"?>
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="purchaseOrder.xsd">
    <order id="001">
        <supplier>
            <companyName>Nike</companyName>
        </supplier>
        <date>26-07-2008</date>
        <status>complete</status>
        <!-- complete, cancelled, pending -->
        <payment>
            <type>cheque</type>
        </payment>
        <item>
            <name>shoe</name>
            <quantity>100</quantity>
            <amount>50000</amount>
        </item>
    </order>
</orders>
