=== muntaswir72562/inventoryHub/public/data/user.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
 
<xs:simpleType name="titleType">
    <xs:restriction base="xs:string">
        <xs:pattern value="mr|mrs|miss"/>
        </xs:restriction>
 </xs:simpleType>

 <xs:simpleType name="userIdType">
    <xs:restriction base="xs:string">
        <xs:pattern value="user[0-9]{3}"/>
    </xs:restriction>
    </xs:simpleType>

    <!-- <xs:simpleType name="passType">
        <xs:restriction base="xs:string">
            <xs:pattern value="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$"/>
        </xs:restriction>
        </xs:simpleType> -->
<!-- Minimum eight characters, at least one uppercase letter, one lowercase letter, one number and one special character:
  ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$ -->

  
<xs:complexType name="addressType">
    <xs:sequence>
        <xs:element name="streetName" type="xs:string" />
        <xs:element name="city" type="xs:string" />
        <xs:element name="postalCode" type="xs:unsignedShort" />
        <xs:element name="country" type="xs:string" />
      </xs:sequence>
</xs:complexType>

<xs:element name="users">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="user">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="firstName" type="xs:string" />
                    <xs:element name="lastName" type="xs:string" />
                  </xs:sequence>
                  <xs:attribute name="title" type="titleType" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="email" type="xs:string" />
              <xs:element name="dob" type="xs:string" />
              <xs:element name="address" type="addressType"/>
              <xs:element name="password" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="id" type="userIdType" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== muntaswir72562/inventoryHub/inventoryhubphp/data/user.xml
<?xml version="1.0" encoding="utf-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="user.xsd">
    <user id="user001">
        <name title="mr">
            <firstName>muntaswir</firstName>
            <lastName>waliyullah</lastName>
        </name>
        <email>mun@gmail.com</email>
        <dob>26/07/01</dob>
        <address>
            <streetName>ave cardinal4</streetName>
            <city>port louis</city>
            <postalCode>11221</postalCode>
            <country>Mauritius</country>
        </address>
        <password>Qw!@123456789</password>
        This is about meee
    </user>

    <user id="user002">
        <name title="mrs">
            <firstName>faar</firstName>
            <lastName>khoda</lastName>
        </name>
        <email>faar@gmail.com</email>
        <dob>24/11/02</dob>
        <address>
            <streetName>ave unknown</streetName>
            <city>vdp</city>
            <postalCode>11225</postalCode>
            <country>Mauritius</country>
        </address>
        <password>Qw!@123456789</password>
    </user>

    </users>
