=== muntaswir72562/inventoryHub/src/data/invoice.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="invType">
    <xs:restriction base="xs:string">
        <xs:pattern value="inv[0-9]{3}"/>
    </xs:restriction>
    </xs:simpleType>

<xs:complexType name="itemType">
    <xs:sequence>
        <xs:element name="productId" type="xs:integer" />
        <xs:element name="name" type="xs:string" />
        <xs:element name="quantity" type="xs:integer" />
        <xs:element name="price" type="xs:decimal" />
    </xs:sequence>
</xs:complexType>

<xs:simpleType name="stsType">
    <xs:restriction base="xs:string">
        <xs:pattern value="paid|draft|not paid"/>
    </xs:restriction>
    </xs:simpleType>

<xs:element name="invoices">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="invoice" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="supplierId" type="xs:integer" />
              <xs:element name="date" type="xs:date" />
              <xs:element name="status" type="stsType" />
              <xs:element name="items">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="item" type="itemType"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="total" type="xs:decimal" />
            </xs:sequence>
            <xs:attribute name="id" type="invType" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== muntaswir72562/inventoryHub/src/data/invoice.xml
<?xml version="1.0" encoding="utf-8"?>
<invoices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="invoice.xsd">
<invoice id="inv001">
    <supplierId>123</supplierId>
    <date>2023-01-30</date>
    <status>paid</status>
    <items>
        <item>
            <productId>101</productId>
            <name>Product 1</name>
            <quantity>2</quantity>
            <price>50.00</price>
        </item>
        <item>
            <productId>102</productId>
            <name>Product 2</name>
            <quantity>1</quantity>
            <price>100.00</price>
        </item>
    </items>
    <total>200.00</total>
</invoice>

</invoices>

=== muntaswir72562/inventoryHub/src/data/purchase_order.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- xsi:noNamespaceSchemaLocation="invoice.xsd" -->
<invoices>
<invoice>
    <id>1</id>
    <customerId>123</customerId>
    <date>2023-01-30</date>
    <status>paid</status><!-- draft, notPaid -->
    
    <items>
        <item>
            <productId>101</productId>
            <name>Product 1</name>
            <quantity>2</quantity>
            <price>50.00</price>
        </item>
        <item>
            <productId>102</productId>
            <name>Product 2</name>
            <quantity>1</quantity>
            <price>100.00</price>
        </item>
    </items>
    <total>200.00</total>
</invoice>

</invoices>
