=== muntaswir72562/inventoryHub/src/data/payment.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="stsType">
    <xs:restriction base="xs:string">
        <xs:pattern value="paid|complete|pending"/>
        </xs:restriction>
</xs:simpleType>

<xs:simpleType name="invType">
    <xs:restriction base="xs:string">
        <xs:pattern value="inv[0-9]{3}"/>
    </xs:restriction>
    </xs:simpleType>
    
<xs:simpleType name="paymentType">
    <xs:restriction base="xs:string">
        <xs:pattern value="cash|cheque|internet banking"/>
        </xs:restriction>
</xs:simpleType>

<xs:element name="payments">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="payment" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="date" type="xs:date" />
              <xs:element name="supplierName" type="xs:string" />
              <xs:element name="invoice">
                <xs:complexType>
                  <xs:attribute name="id" type="invType" use="required" />
                </xs:complexType>
              </xs:element>
              <xs:element name="amount" type="xs:decimal" />
              <xs:element name="status" type="stsType" />
              <xs:element name="payment" type="paymentType" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== muntaswir72562/inventoryHub/src/data/payment.xml
<?xml version="1.0" encoding="utf-8"?>
<payments xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="payment.xsd">
    <payment>
        <date>2023-01-30</date>
        <supplierName>Nike</supplierName>
        <invoice id="inv001"/>
        <amount>50000</amount>
        <status>paid</status>
        <payment>cash</payment>
       
    </payment>
    
</payments>
